Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2018-12, with the labels that each got.

#37 Do not use `cp -a` as it fails inside container.
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#39 Shorten config resource name
  bindata/v3.11.0/kube-scheduler/cm.yaml
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#41 Add priority class to static scheduler pod and its operator pods.
  bindata/v3.11.0/kube-scheduler/pod.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#42 bindata: add memory request to kube-scheduler pod
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#43 manifests: add memory request to operator pod
  manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#40 Add an e2e test for verifying that cluster-kube-scheduler-operator deployment is up.
  Makefile
  test/e2e/main_test.go
Labels: approved, lgtm, size/M
