Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2018-10, with the labels that each got.

#8 update manifest files name.
  manifests/0000_11_cluster-kube-scheduler-operator_00_namespace.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_01_config.crd.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_02_config.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_03_configmap.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_04_clusterrolebinding.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_05_serviceaccount.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
Labels: approved, size/XS

#9 Add manifests/image-references
  manifests/image-references
Labels: approved, size/XS

#10 Fix error messages.
  cmd/cluster-kube-scheduler-operator/render/render.go
Labels: approved, size/XS

#11 Remove CloudProviderHostPath to make render sub command work.
  bindata/bootkube/manifests/kube-scheduler-daemonset.yaml
Labels: approved, size/XS

#14 Run kube-scheduler and its operator on masters.
  bindata/v3.11.0/kube-scheduler/deployment.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#15 Fix nil pointer
  cmd/cluster-kube-scheduler-operator/render/render.go
Labels: approved, lgtm, size/XS

#16 Make sure the namespace is created first
  bindata/bootkube/manifests/00_openshift-kube-scheduler-ns.yaml
Labels: approved, lgtm, size/XS

#13 Fix verify generated bin data script
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
Labels: approved, lgtm, size/S

#19 add mfojtik to owners
  OWNERS
Labels: approved, lgtm, size/XS

#20 render: remove --config-override-file default and pluralize
  cmd/cluster-kube-scheduler-operator/render/render.go
Labels: approved, lgtm, size/M

#21 Unify kube-scheduler-config configmap names
  bindata/bootkube/manifests/kube-system-kube-scheduler-config.yaml
  bindata/v3.11.0/kube-scheduler/cm.yaml
  bindata/v3.11.0/kube-scheduler/deployment.yaml
  hack/update-generated-bindata.sh
Labels: approved, lgtm, size/XS

#23 Fix auto generated bin data.
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#22 Update cluster-kube-scheduler-operator
  bindata/bootkube/manifests/kube-scheduler-daemonset.yaml
  bindata/v3.11.0/kube-scheduler/operator-config.yaml
  glide.lock
  manifests/0000_11_cluster-kube-scheduler-operator_01_config.crd.yaml
  manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
  manifests/image-references
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_kubescheduler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/test/assets_test.go
  vendor/github.com/openshift/api/authorization/OWNERS
  vendor/github.com/openshift/api/oauth/OWNERS
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/OWNERS
  vendor/github.com/openshift/api/user/OWNERS
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/openshift/library-go/OWNERS
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/hack/verify-golint.sh
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/XL

#24 render: switch to generic command from library-go
  bindata/bootkube/manifests/kube-system-kube-scheduler-config.yaml
  cmd/cluster-kube-scheduler-operator/render/config.go
  cmd/cluster-kube-scheduler-operator/render/render.go
  glide.lock
  pkg/test/assets_test.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/args_test.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
Labels: approved, lgtm, size/L
