Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-09, with the labels that each got.

#168 Bug 1749457: Add master_schedulable metric
  pkg/operator/configmetrics/configmetrics.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#170 Move v3.11.0 to v4.1.0
  Makefile
  README.md
  bindata/v4.1.0/kube-scheduler/cm.yaml
  bindata/v4.1.0/kube-scheduler/defaultconfig-postbootstrap.yaml
  bindata/v4.1.0/kube-scheduler/defaultconfig.yaml
  bindata/v4.1.0/kube-scheduler/kubeconfig-cm.yaml
  bindata/v4.1.0/kube-scheduler/leader-election-rolebinding.yaml
  bindata/v4.1.0/kube-scheduler/ns.yaml
  bindata/v4.1.0/kube-scheduler/pod-cm.yaml
  bindata/v4.1.0/kube-scheduler/pod.yaml
  bindata/v4.1.0/kube-scheduler/policyconfigmap-role.yaml
  bindata/v4.1.0/kube-scheduler/policyconfigmap-rolebinding.yaml
  bindata/v4.1.0/kube-scheduler/sa.yaml
  bindata/v4.1.0/kube-scheduler/scheduler-clusterrolebinding.yaml
  bindata/v4.1.0/kube-scheduler/svc.yaml
  cmd/render/render.go
  pkg/operator/target_config_reconciler_v410_00.go
  pkg/operator/target_config_reconciler_v410_00_test.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm, size/L

#169 Fix makefile to allow make images to work
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, lgtm, size/S

#158 [release-4.1] Bug 1729918: Switch to configobserver pattern
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/configobservation/scheduler/observe_scheduler_test.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#173 Bug 1749457: match servicemonitor label with actual label on service
  manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#175 Switch to genericoperatorclient
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v410_00.go
Labels: approved, lgtm, size/M

#177 Update README.md
  README.md
Labels: approved, lgtm, size/M
