Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-03, with the labels that each got.

#68 Change kubescheduler type name from instance to cluster
  bindata/v3.11.0/kube-scheduler/operator-config.yaml
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#69 switch to pull if not present from always
  bindata/v3.11.0/kube-scheduler/pod.yaml
  manifests/0000_11_kube-scheduler-operator_06_deployment.yaml
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#70 Switch to getting policy configmap name from api
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/M

#73 minor fitting to set versions for our operator
  manifests/0000_11_kube-scheduler-operator_03_version-mapping.yaml
  manifests/0000_11_kube-scheduler-operator_06_deployment.yaml
  manifests/0000_11_kube-scheduler-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/S

#76 Policy configmap working with kube-scheduler
  bindata/v3.11.0/kube-scheduler/policyconfigmap-role.yaml
  bindata/v3.11.0/kube-scheduler/policyconfigmap-rolebinding.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#80 force scheduler insecure
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS
