Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-07, with the labels that each got.

#150 Add scheduler readme
  README.md
Labels: approved, lgtm, size/M

#149 manifests: add ServiceMonitor for kube-scheduler
  bindata/v3.11.0/kube-scheduler/servicemonitor.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#151 Add Mike to reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#153 move kube-scheduler servicemonitor to manifests
  bindata/v3.11.0/kube-scheduler/ns.yaml
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#136 Get policy configmap using config observer pattern instead of relying on static config file
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/configobservation/scheduler/observe_scheduler_test.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  test/e2e/scheduler_test.go
Labels: approved, lgtm, size/L

#155 Fix to have hardcoded configmap name in the scheduler config
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/configobservation/scheduler/observe_scheduler_test.go
Labels: approved, lgtm, size/M
