Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-05, with the labels that each got.

#122 Make installer controller wait for required resources to exists before running installer pod
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/sigs.k8s.io/controller-tools/Gopkg.lock
  vendor/sigs.k8s.io/controller-tools/Gopkg.toml
Labels: approved, lgtm, size/L

#123 Add missing revision suffix when checking for required resources
  glide.lock
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/L

#120 change initial loglevel to align with logging controller defaults
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#125 Update library-go
  glide.lock
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/M

#124 Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Labels: approved, lgtm, size/S

#129 remove whitespaces
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#128 Bug 1705645: Allow configmap resourcelock creation in openshift-kube-scheduler namespace
  bindata/v3.11.0/kube-scheduler/configmap-leaderelection-rolebinding.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap.yaml
  bindata/v3.11.0/kube-scheduler/leader-election-configmap-role.yaml
  bindata/v3.11.0/kube-scheduler/leader-election-rolebinding.yaml
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#131 Remove old values from operator config CR
  manifests/0000_25_kube-scheduler-operator_02_operator.cr.yaml
Labels: approved, lgtm, size/XS

#134 Vendor bump to library-go fixes
  glide.lock
  vendor/github.com/gobuffalo/envy/SHOULDERS.md
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/envy_test.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/exec_path_change.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/values.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testscript.go
  vendor/github.com/rogpeppe/go-internal/testscript/testscript_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#112 Small refactor
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/S

#135 Remove unnecessary rules
  bindata/v3.11.0/kube-scheduler/configmap-leaderelection-rolebinding.yaml
  bindata/v3.11.0/kube-scheduler/leader-election-configmap-role.yaml
  bindata/v3.11.0/kube-scheduler/policyconfigmap-role.yaml
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L
