Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-02, with the labels that each got.

#58 update clusteroperator name to kube-scheduler
  manifests/0000_11_kube-scheduler-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS

#57 Add configmap in openshift-config namespace and watch it
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#64 move from componentconfig/v1alpha1 to kubescheduler.config.k8s.io/v1alpha1
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#62 Rotate kubeconfig
  bindata/bootkube/manifests/kube-scheduler-secret-kubeconfig.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml
  bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap.yaml
  bindata/v3.11.0/kube-scheduler/kubeconfig-cm.yaml
  bindata/v3.11.0/kube-scheduler/leader-election-rolebinding.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#65 Don't pass nil function pointer to NewConfigObserver
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: approved, lgtm, size/XS
