Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-08, with the labels that each got.

#161 Clean up dead code
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/S

#163 manifests: fix apiVersion for operator config
  manifests/0000_25_kube-scheduler-operator_03_configmap.yaml
Labels: approved, lgtm, size/XS

#164 Bug 1736795: Add check for removal of policy configmap
  glide.lock
  pkg/operator/configobservation/scheduler/observe_scheduler.go
  pkg/operator/configobservation/scheduler/observe_scheduler_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/google.golang.org/appengine/README.md
  vendor/google.golang.org/appengine/capability/capability.go
  vendor/google.golang.org/appengine/datastore/internal/cloudkey/cloudkey.go
  vendor/google.golang.org/appengine/datastore/internal/cloudpb/entity.pb.go
  vendor/google.golang.org/appengine/datastore/key.go
  vendor/google.golang.org/appengine/datastore/keycompat.go
  vendor/google.golang.org/appengine/datastore/keycompat_test.go
  vendor/google.golang.org/appengine/file/file.go
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_test.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#165 Update OWNERS file to add new reviewers/approvers
  OWNERS
Labels: approved, lgtm, size/XS

#166 bootstrap: log to /var/log/bootstrap-control-plane/kube-scheduler.log
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm, size/S

#167 Bug 1745671: use cached clients in resource syncer
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
