Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-11, with the labels that each got.

#176 Bug 1745671: Do not register event handlers twice for configmaps under openshift-kube-scheduler
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#183 Fix scheduler metrics
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
  pkg/operator/configmetrics/configmetrics.go
Labels: approved, lgtm, size/S

#184 bump(*): library-go for fileobserver
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#185 Add manifest annotations for hosted deployment exclusions
  manifests/0000_25_kube-scheduler-operator_02_service.yaml
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
  manifests/0000_25_kube-scheduler-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Labels: approved, lgtm, size/S

#189 bump(*): library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#190 Bug 1735509: monitoring: move service monitor RBAC rules to manifests/
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#182 Bug 1735509: monitoring: move service monitor RBAC rules to manifests/
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, size/M
