Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-06, with the labels that each got.

#139 Test to check scheduler configmap working or not
  test/e2e/main_test.go
  test/e2e/scheduler_test.go
Labels: approved, lgtm, size/L

#140 Fix operator status
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/M

#143 Remove degraded
  pkg/operator/staleconditions/remove_stale_conditions.go
  pkg/operator/starter.go
  test/e2e/scheduler_test.go
Labels: approved, lgtm, size/L

#142 remove stale condition set by accident in 4.1.0
  pkg/operator/staleconditions/remove_stale_conditions.go
  pkg/operator/starter.go
Labels: size/L

#144 Switch to go 1.12
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS
