Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-01, with the labels that each got.

#46 Add ravi to owners
  OWNERS
Labels: approved, lgtm, size/XS

#47 Remove cluster- from kube-scheduler operator
  manifests/0000_11_cluster-kube-scheduler-operator_05_serviceaccount.yaml
  manifests/0000_11_kube-scheduler-operator_00_namespace.yaml
  manifests/0000_11_kube-scheduler-operator_01_config.crd.yaml
  manifests/0000_11_kube-scheduler-operator_03_configmap.yaml
  manifests/0000_11_kube-scheduler-operator_04_clusterrolebinding.yaml
  manifests/0000_11_kube-scheduler-operator_05_serviceaccount.yaml
  manifests/0000_11_kube-scheduler-operator_06_deployment.yaml
  pkg/operator/starter.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/M

#51 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#49 Makefile: switch to library-go build system
  .travis.yml
  Makefile
  hack/boilerplate.txt
  hack/build-cross.sh
  hack/build-go.sh
  hack/build-images.sh
  hack/build-rpms.sh
  hack/cherry-pick.sh
  hack/deps
  hack/env
  hack/import-restrictions.json
  hack/lib/build/archive.sh
  hack/lib/build/binaries.sh
  hack/lib/build/environment.sh
  hack/lib/build/images.sh
  hack/lib/build/release.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/cleanup.sh
  hack/lib/cmd.sh
  hack/lib/compress.awk
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/test/junit.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/golang.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  hack/move-upstream.sh
  hack/push-release.sh
  hack/test-go.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/update-generated-bindata.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-govet.sh
  hack/verify-imports.sh
  hack/verify-upstream-commits.sh
Labels: approved, lgtm, size/XXL

#52 Add Seth/Stefan to owners
  OWNERS
Labels: approved, lgtm, size/XS

#48 Remove disablephase2 flag.
  cmd/render/render.go
Labels: approved, lgtm, size/XS
