Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2019-04, with the labels that each got.

#77 Set cert-dir to prepare for 1.13
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#87 Upgrade fix
  glide.lock
  glide.yaml
  manifests/0000_11_kube-scheduler-operator_03_version-mapping.yaml
  manifests/0000_11_kube-scheduler-operator_06_deployment.yaml
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/quota/v1/generated.proto
  vendor/github.com/openshift/api/quota/v1/types.go
  vendor/github.com/openshift/api/tools/genswaggertypedocs/swagger_type_docs.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/exec_path_change.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testdata/values.txt
  vendor/github.com/rogpeppe/go-internal/testscript/testscript.go
  vendor/github.com/rogpeppe/go-internal/testscript/testscript_test.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/example_embedded_test.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: approved, lgtm, size/XXL

#88 Disable insecure port
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/v3.11.0/kube-scheduler/pod.yaml
  bindata/v3.11.0/kube-scheduler/svc.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#89 kube-scheduler: config authnz settings
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#94 prevent panic in logging message
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/XS

#72 Get feature gates and using them while starting kube-scheduler
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/target_config_reconciler_v311_00_test.go
Labels: approved, lgtm, size/L

#96 revert cert rotation metrics
  glide.lock
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/monitor.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, lgtm, size/XXL

#99 Fix sorting in featuregates
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/target_config_reconciler_v311_00_test.go
Labels: approved, lgtm, size/M

#97 pod.yaml: wire serving-cert secret
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler_v311_00.go
Labels: approved, lgtm, size/S

#90 Wait for port to be available
  bindata/v3.11.0/kube-scheduler/pod.yaml
  manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
  pkg/operator/target_config_reconciler_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#102 Switch to go 1.11
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#105 speed up leader election
  glide.lock
  pkg/operator/target_config_reconciler_v311_00_test.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/S

#107 Use the CVO for operator config
  manifests/0000_11_kube-scheduler-operator_02_operator.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#110 Change one of the ports to be checked to 10259
  bindata/v3.11.0/kube-scheduler/pod.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#115 Add node-selector annotation to namespace
  bindata/bootkube/manifests/00_openshift-kube-scheduler-ns.yaml
  bindata/v3.11.0/kube-scheduler/ns.yaml
  manifests/0000_11_kube-scheduler-operator_00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, size/XS

#118 Move component to an appropriate upgrade order (kube sched)
  manifests/0000_25_kube-scheduler-operator_00_namespace.yaml
  manifests/0000_25_kube-scheduler-operator_01_config.crd.yaml
  manifests/0000_25_kube-scheduler-operator_02_operator.cr.yaml
  manifests/0000_25_kube-scheduler-operator_02_service.yaml
  manifests/0000_25_kube-scheduler-operator_03_configmap.yaml
  manifests/0000_25_kube-scheduler-operator_04_clusterrolebinding.yaml
  manifests/0000_25_kube-scheduler-operator_05_serviceaccount.yaml
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
  manifests/0000_25_kube-scheduler-operator_07_clusteroperator.yaml
Labels: approved, lgtm, size/XS
