Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2020-12, with the labels that each got.

#288 Bug 1881322: Sync new kube-scheduler-client-cert-key on recovery
  bindata/v4.1.0/kube-scheduler/pod.yaml
  cmd/cluster-kube-scheduler-operator/main.go
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#309 Annotate manifests for single-node-developer cluster profile
  manifests/0000_25_kube-scheduler-operator_00_namespace.yaml
  manifests/0000_25_kube-scheduler-operator_02_operator.cr.yaml
  manifests/0000_25_kube-scheduler-operator_02_service.yaml
  manifests/0000_25_kube-scheduler-operator_03_configmap.yaml
  manifests/0000_25_kube-scheduler-operator_04_clusterrolebinding.yaml
  manifests/0000_25_kube-scheduler-operator_05_serviceaccount.yaml
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
  manifests/0000_25_kube-scheduler-operator_07_clusteroperator.yaml
  manifests/0000_90_kube-scheduler-operator_01_prometheusrole.yaml
  manifests/0000_90_kube-scheduler-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Labels: approved, lgtm

#310 Bug 1905327: specify cpu and memory resources for initContainers
  bindata/v4.1.0/kube-scheduler/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#283 Bug 1907998: Collect /metrics/resources from scheduler
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
  test/e2e/scheduler_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
