Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2020-06, with the labels that each got.

#251 Bug 1801437: bump(*): Mark Abandoned static pod revisions
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#253 update openshift/api for IPv6DualStackNoUpgrade featureset
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#256 [release-4.3] Bug 1848583: bump(library-go): Add resource requests to installer/pruner pods
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
