Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2020-03, with the labels that each got.

#220 [release-4.3] Bug 1810184: Fix dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#221 [release-4.2] Bug 1810185: Fix dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#222 [release-4.4] Bug 1810182: Remove wildcard COPY form Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#215 Add tnozicka
  OWNERS
Labels: approved, lgtm, size/XS

#214 Bug 1810181: Remove wildcard COPY form Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#223 [release-4.1] Bug 1810186: Remove wildcard COPY form Dockerfile
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#227 Bug 1812583: Normalize CPU requests on masters
  bindata/v4.1.0/kube-scheduler/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#229 bump library-go to migrate controllers to factory
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/controller/manager/controller_manager.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#230 bootstrap: set log-level 2 instea of 0
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm
