Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2021-04, with the labels that each got.

#340 servicemonitor: Relabel kube_pod_resource_* pod/namespace labels
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Labels: approved, lgtm

#344 Bug 1948431: Bump openshift/api to get the necessary CSIMigration feature gates
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/install.go
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_deprecatedapirequests.yaml
  vendor/github.com/openshift/api/apiserver/v1/doc.go
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_deprecatedapirequest.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#345 bug 1949364: Mention scheduling profiles
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#343 Add management workload annotations
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/bootkube/manifests/00_openshift-kube-scheduler-ns.yaml
  bindata/v4.1.0/kube-scheduler/ns.yaml
  bindata/v4.1.0/kube-scheduler/pod.yaml
  manifests/0000_25_kube-scheduler-operator_00_namespace.yaml
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#348 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#347 Rename workload annotations
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  bindata/v4.1.0/kube-scheduler/pod.yaml
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#346 Bug 1954087: added test for manage config maps in targetconfigcontroller
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
