Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2021-02, with the labels that each got.

#326 Bug 1920619: bump(*): remove default scheduler profile
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#328 Remove tnozicka and ravi from OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#330 Bug 1926579: Move warning about deprecated spec.policy field
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#331 bug 1844989: Allow to set --tls-cipher-suites and --tls-min-version of KS instances through observed config
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#332 bug 1844989: Set --tls-cipher-suites, resp. --tls-min-version only when the fields under servingInfo observedConfig are found
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
