Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2021-01, with the labels that each got.

#311 Bug 1908145: Change recovery-controller port to avoid conflicts
  bindata/v4.1.0/kube-scheduler/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#313 Bug 1887392: bump kube to 1.201 and lib-go to master to pick up authn/z caching
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/api/authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#319 Bug 1891068: manifests: add missing profile annotations
  manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#316 bug 1889488: Have probes listen to secure ports
  bindata/v4.1.0/kube-scheduler/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#315 Bug 1903586: Sync new kube-scheduler-client-cert-key on recovery
  bindata/v4.1.0/kube-scheduler/pod.yaml
  cmd/cluster-kube-scheduler-operator/main.go
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#314 [release-4.6] Bug 1891742: bump(library-go): controller/staticpod: reduce noise of …
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#317 Bug 1915363: Sync new kube-scheduler-client-cert-key on recovery
  bindata/v4.1.0/kube-scheduler/pod.yaml
  cmd/cluster-kube-scheduler-operator/main.go
  pkg/cmd/recoverycontroller/cmd.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#324 bug 1920509: Use ss instead of lsof when waiting for ports
  bindata/v4.1.0/kube-scheduler/pod.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
