Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2021-03, with the labels that each got.

#333 bug 1934154: Bump github.com/gogo/protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#335 bug 1938468: Specify cpu resource request for kube-scheduler-operator-container container
  manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#334 bug 1924490: Bump github.com/gogo/protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#338 defines test-e2e-preferred-host job for running smoke tests to check if KS talks to Kube over a preferred host
  Makefile
  test/e2e-preferred-host/ks_preferred_host_kas_test.go
Labels: approved, lgtm

#339 Fix development readme to refer to actual pod/container
  README.md
Labels: approved, lgtm
