Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2022-01, with the labels that each got.

#373 bug 2005901: Guard controller pdb
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#394 Bug 2038968: bump(openshift/api): to get CSI migration gates switched off
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml-patch
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#396 bug 2005901: Bump library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#392 bug 2035927: Replace NodeResourcesLeastAllocated/NodeResourcesMostAllocated plugins with NodeResourcesFit
  README.md
  bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#398 Bug 2040132: drop --port flag
  bindata/assets/kube-scheduler/pod.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#400 bug 2037665: Set upgradeable=false if using Policy field
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#390 Bug 2033751: Return Error when trying to use Scheduler Policy
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#397 bug 2005901: Sync the library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/test/library/metrics/query.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#395 Bug 2039414: Update KubeSchedulerConfig to v1beta3(default in 1.23)
  bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
  bindata/assets/config/defaultconfig-postbootstrap-lownodeutilization.yaml
  bindata/assets/config/defaultconfig-postbootstrap-noscoring.yaml
  bindata/assets/config/defaultconfig.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#402 bug 2037665: Remove policy upgradeable when policy field cleared
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#403 bug 2037665: Check policy name field independently of the configmap change
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#393 Bug 2035986: Replace deprecated annotation
  bindata/assets/kube-scheduler/pod.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
