Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2022-11, with the labels that each got.

#445 bootstrap-kube-scheduler: specify resources.requests
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm

#446 OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
  go.mod
  go.sum
  pkg/test/assets_test.go
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#448 OCPBUGS-4292: bootstrap-kube-scheduler: specify resources.requests
  bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
