Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2022-02, with the labels that each got.

#407 bug 2029470: update library-go to get rapid installer pod fixes
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#409 update cert injection annotations to beta
  bindata/assets/kube-scheduler/svc.yaml
  manifests/0000_25_kube-scheduler-operator_02_service.yaml
Labels: approved, lgtm

#410 Do not wait for a port which is no longer used by the scheduler
  bindata/assets/kube-scheduler/pod.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
Labels: approved, lgtm

#411 Bump(openshift/api): to get CSI changes
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#412 Update resourcelock to configmapleases
  bindata/assets/config/defaultconfig.yaml
Labels: approved, lgtm

#408 bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved, backport-risk-assessed

#415 Bug 2053582: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/utils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#416 Bug 2053268: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/utils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed

#417 Bug 2053582: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#418 Bug 2053268: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed
