Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2023-09, with the labels that each got.

#492 Bump openshift/* libs
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/modules.txt
Labels: approved, lgtm, acknowledge-critical-fixes-only

#498 bump(openshift/client-go,library-go)
  go.mod
  go.sum
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/doc.go
  vendor/modules.txt
Labels: approved, lgtm

#497 [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
  pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
