Repository openshift/cluster-kube-scheduler-operator, pull requests merged in 2023-11, with the labels that each got.

#508 OCPNODE-1886: Migrate from kubescheduler.config.k8s.io/v1beta3 to v1
  bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
  bindata/assets/config/defaultconfig-postbootstrap-lownodeutilization.yaml
  bindata/assets/config/defaultconfig-postbootstrap-noscoring.yaml
  bindata/assets/config/defaultconfig.yaml
  bindata/bootkube/config/bootstrap-config-overrides.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#507 NO-JIRA: README.md: steps for enabling profiling, collecting heap and running go tool pprof
  README.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#512 OCPBUGS-23463: bump(library-go)
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#511 OCPBUGS-24218: Annotate serviceaccount-ca with ownership information
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
